# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65daca16a6d1ba785c6ee2c2f86d4350ee439747fefaf7e3e64c87edee9616d615a99384895719c33e003c89ba5dbc3da1bf090fa0cc2bf31e217b5ec37d5692

test:
  secret_key_base: d139747d24980267078e3f1e5de05e4f15279a4f0ea7c8e7250187f512ad17276c1b21fae890c73a9fec7c495e547180c2f3902bb85ee8fc031a97a74ae673bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
